dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
notifications:
  email: false
  webhooks:
    urls:
      - 'https://webhook.atomist.com/atomist/travis/teams/T5964N9B7'
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.m2"
